server:
  port: 8070
spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/tanhaodi/repo1.git  # 远程git仓库的地址
            username: tanhaodi@163.com  # 以及相应的账户名
            password: tan820507  # 和密码
            basedir: E:\basedir  # 可以使用这个配置项来指定本地git仓库的路径
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
